export const UPDATE_FINAL_MAP = "UPDATE_FINAL_MAP";
export const UPDATE_TMP_MAP = "UPDATE_TMP_MAP";
export const UPDATE_TETRIMINOS_POS = "UPDATE_TETRIMINOS_POS";
export const TETRI_ROTATION = 'TETRI_ROTATION';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_ROOM = 'UPDATE_ROOM';