export const SET_GAME_ROOM = 'SET_GAME_ROOM';
export const GAME_ROOM_RESET = 'GAME_ROOM_RESET';

export const SET_GAME_ROOM_LEADERBOARD = 'SET_GAME_ROOM_LEADERBOARD';
export const SET_GAME_ROOM_STATE = 'SET_GAME_ROOM_STATE';
export const SET_GAME_ROOM_OWNER = 'SET_GAME_ROOM_OWNER';

export const GAME_ROOM_INIT_STATE = 'GAME_ROOM_INIT_STATE';

export const GAME_ROOM_UPD_SHADOW = 'GAME_ROOM_UPD_SHADOW';