export const GAME_RESET_CURRMAP = 'GAME_RESET_CURRMAP';
export const INCR_NB_LINE_BLOCK = 'INCR_NB_LINE_BLOCK';
export const SET_NB_LINE_BLOCK = 'SET_NB_LINE_BLOCK'; 
export const UPDATE_FINAL_MAP = "UPDATE_FINAL_MAP";

export const UPDATE_TETRIMINOS_POS = "UPDATE_TETRIMINOS_POS";
export const TETRI_ROTATION = 'TETRI_ROTATION';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_ROOM = 'UPDATE_ROOM';

export const GAME_RESET = 'GAME_RESET';

export const GAME_INIT_STATE = 'GAME_INIT_STATE';

export const GAME_INCR_SCORE = 'GAME_INCR_SCORE';