export const SOCKET_SEND_USERNAME = 'SOCKET_SEND_USERNAME';
export const SOCKET_RECV_USERNAME = 'SOCKET_RECV_USERNAME';
export const SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM';
export const SOCKET_CONFIRM_JOIN_ROOM = 'SOCKET_CONFIRM_JOIN_ROOM';
export const SOCKET_GET_ALL_ROOMS = 'SOCKET_GET_ALL_ROOMS';

export const SOCKET_ALL_ROOMS = 'SOCKET_ALL_ROOM';

export const SOCKET_NEW_ROOM = 'SOCKET_NEW_ROOM';

export const SOCKET_GET_NEXT_TETRIMINOS = 'SOCKET_GET_NEXT_TETRIMINOS';

export const SOCKET_RUN_GAME = 'SOCKET_RUN_GAME';

export const SOCKET_UPDATE_ROOM = 'SOCKET_UPDATE_ROOM';

export const SOCKET_SEND_TETRIMINOS = 'SOCKET_SEND_TETRIMINOS';

export const SOCKET_JOIN_ROOM_WT_NAME = 'SOCKET_JOIN_ROOM_WT_NAME';

export const SOCKET_USER_DEAD = 'SOCKET_USER_DEAD'; 

export const SOCKET_PATCH_USER = 'SOCKET_PATCH_USER';

export const SOCKET_PATCH_ROOM = 'SOCKET_PATCH_ROOM';

export const SOCKET_UPDATE_USER_TETRI_BOARD = 'SOCKET_UPDATE_USER_TETRI_BOARD';

export const SOCKET_LEAVE_ROOM = 'SOCKET_LEAVE_ROOM';

export const SOCKET_DELETE_ROOM = 'SOCKET_DELETE_ROOM';

// launch new party  on the same room go back on basic state
export const SOCKET_PLAY_AGAIN = 'SOCKET_PLAY_AGAIN';

export const SOCKET_RESET_ROOM = 'SOCKET_RESET_ROOM';

export const SOCKET_LINE_DELETE = 'SOCKET_LINE_DELETE';