export const ADD_TETRI = 'ADD_TETRI';
export const REMOVE_FIRST_TETRI = 'REMOVE_FIRST_TETRI';
export const RESET_TETRI = 'RESET_TETRI';
export const REMOVE_FIRST_TETRI_AND_RESET_ROTATION = 'REMOVE_FIRST_TETRI_AND_RESET_ROTATION';
export const END_TURN_PUT = 'END_TURN_PUT';
